# location of server. Used as salt for generating user ID

hostname = "127.0.0.1"

# Server port

port = 8080

# Whether to use https. Use 'false' if you are running the server on a PaaS

secure = true

# Custom header that some PaaS uses to indicate client IP

IPheader = ""

# Initial password at server setup. Will be reset after first run

password = "admin"

# Page size when listing peers

pageSize = 50

# always set this to true

production = true

[redis]

# ### Redis datastore configuration ###

host = "127.0.0.1"
port = 6379
password = ""

[security]

# ### Security Related configuration ###
# Don't mess with these unless you know what you are doing!!

# ID byte length

IDLength = 8 # 64bit

# Length of salt used for generating id from user name

saltLength = 8 # 64bit

# Token expiration time

tokenTTL = 300 # 5min
tokenLength = 64 # 256bit

# Hash related config

hashIterations = 37
hashLength = 64 # 256bit
