# location of server. Used as salt for generating user ID

production = true

hostname = "127.0.0.1"

# Server port

port = 8080

# Custom header that some PaaS uses to indicate client IP

IPheader = ""

# Initial password at server setup. Will be reset after first run

password = "admin"


# Page size when listing peers

pageSize = 50

[redis]

# ### Redis datastore configuration ###

host = "127.0.0.1"
port = 6379
password = ""

[security]

# ### Security Related configuration ###
# Don't mess with these unless you know what you are doing!!

# ID byte length

IDLength = 8 # 64bit

# Length of salt used for generating id from user name

saltLength = 8 # 64bit

# Token expiration time

tokenTTL = 300 # 5min
tokenLength = 64 # 256bit

# Hash related config

hashIterations = 37
hashLength = 64 # 256bit